/*
 * Room Reservation API
 *
 * A Simple IP Address API
 *
 * OpenAPI spec version: 0.1.9
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using IO.Swagger.Attributes;
using IO.Swagger.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace IO.Swagger.Controllers
{
	[Route("api/[controller]")]
    [ApiController]
    public class LocationApiController : ControllerBase
    {
        private readonly ProjectContext _context;

        public LocationApiController(ProjectContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Returns a list of locations
        /// </summary>
        /// <response code="200">A json array locations</response>
        /// <response code="404">Location not found</response>
        [HttpGet]
        [Route("/api/locations")]
        [ValidateModelState]
        [SwaggerOperation("LocationsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Location>), description: "A json array locations")]
        public async Task<ActionResult<IEnumerable<Location>>> LocationsGet()
        {
            var locations = await _context.Locations
               .Include(location => location.MeetingRooms)
               .Include(location => location.City)
               .Include(location => location.WorkingSpots)
                   .ThenInclude(spot => spot.WorkingSpotReservations)
                       .ThenInclude(reservation => reservation.User)
                           .ThenInclude(user => user.Job)
               .AsNoTracking().ToListAsync();

            if (locations == null)
            {
                return NotFound();
            }

            return locations;
        }
    }
}
